spring.application.name=ai-knowledge-platform

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# TODO This is optional, test and decide if it's needed
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
